baseURL = 'https://evansosenko.com/'
languageCode = 'en-US'
title = 'Evan Sosenko'
theme = 'default'
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[[module.mounts]]
  source = 'content/dev'
  target = 'assets'

[params]
author = "Evan Sosenko"
languageDir = 'ltr'
images = ["avatar.png"]
posthog.api = "/_ph"
posthog.key = "phc_6chuBqaboGyoUo5cEmK9j18371Yw99MFagIPj0Hoq3Y"
