baseURL = 'https://evansosenko.com/'
languageCode = 'en-US'
title = 'Evan Sosenko'
theme = 'default'
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
author = "Evan Sosenko"
production = false
languageDir = 'ltr'
