baseURL = 'https://evansosenko.com/'
locale = 'en-US'
title = 'Evan Sosenko'
theme = 'foundation'
enableRobotsTXT = true
disableKinds = ["rss", "taxonomy", "term"]

[params]
author = "Evan Sosenko"
languageDir = 'ltr'
mainClass = 'container'
images = ["avatar.png"]

remoteCss = [
  "https://cdnjs.cloudflare.com/ajax/libs/picocss/2.1.1/pico.classless.min.css"
]

remoteJs = []

css = [
  "css/theme.css",
  "css/fontawesome.css",
  "css/main.css"
]

js = [
  "js/theme.js",
  "js/modal.js",
  "js/gamer.js"
]

theme.color = "#00a2e8"
theme.lightIcon = "img/fa/sparkles-duotone.svg"
theme.darkIcon = "img/fa/moon-stars-duotone.svg"
theme.notfoundIcon = "galaxy-duotone"
theme.linkIcon = "link-duotone"
theme.extLinkIcon = "arrow-up-right-from-square-duotone"
theme.modalCloseIcon = "circle-xmark-duotone"

[security]
  [security.funcs]
    getenv = ["CONTEXT"]

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
