baseURL = 'https://evansosenko.com/'
languageCode = 'en-US'
title = 'Evan Sosenko'
theme = 'default'
enableRobotsTXT = true
disableKinds = ["rss", "taxonomy", "term"]

[params]
author = "Evan Sosenko"
languageDir = 'ltr'
images = ["avatar.png"]
posthog.api = "/_ph"
posthog.key = "phc_6chuBqaboGyoUo5cEmK9j18371Yw99MFagIPj0Hoq3Y"

[security]
  [security.funcs]
    getenv = ["CONTEXT"]

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
