[tools]
biome = "2.5.12"
hugo = "0.165.0"

[tasks.ci]
description = "Run CI checks"
run = "biome ci"

[tasks.update-baseplate]
description = "Update Hugo Baseplate"
run = "hugo mod get github.com/razor-x/hugo-baseplate@latest && hugo mod vendor"

[tasks.build]
description = "Build the site"
run = "hugo build"

[tasks.dev]
description = "Run the development server"
run = "hugo serve"

[tasks.check]
description = "Check with Biome"
run = "biome check"

[tasks.fix]
description = "Fix with Biome"
run = "biome check --fix"
