[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.4"

[[headers]]
  for = "/*"

  [headers.values]
    Content-Language = "en-US"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'"
    Strict-Transport-Security = "max-age=63072000; includeSubdomains; preload"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), camera=(), microphone=(), payment=()"

[[headers]]
  for = "img/*"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/deck-doctoral-thesis/*"
  to = "https://evansosenko.github.io/deck-doctoral-thesis/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/deck-tmdsc/*"
  to = "https://evansosenko.github.io/deck-tmdsc/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/deck-ucr-exam/*"
  to = "https://evansosenko.github.io/deck-ucr-exam/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/deck-dichalcogenides-superconductivity/*"
  to = "https://evansosenko.github.io/deck-dichalcogenides-superconductivity/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/deck-spin-lifetime/*"
  to = "https://evansosenko.github.io/deck-spin-lifetime/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/curriculum-vitae/*"
  to = "https://evansosenko.github.io/curriculum-vitae/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/pico.min.css.map"
  to = "https://unpkg.com/@picocss/pico@1.5.5/css/pico.min.css.map"
  status = 200
  force = true
