[build]
  command = "hugo --gc --minify --baseURL $DEPLOY_URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.102.3"

[context.production.environment]
HUGO_ENV = "production"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), camera=(), microphone=(), payment=()"
