[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.102.3"

[context.production.environment]
HUGO_ENV = "production"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'"
    Strict-Transport-Security = "max-age=63072000; includeSubdomains; preload"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), camera=(), microphone=(), payment=()"

[[headers]]
  for = "/*.css"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.js"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.png"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[redirects]]
  from = "/deck-doctoral-thesis/*"
  to = "https://evansosenko.com/deck-doctoral-thesis/:splat"
  status = 200
  force = true
