[params]
production = false

themeColor = "#5bcefaff"

remoteCss = [
  "https://cdnjs.cloudflare.com/ajax/libs/modern-normalize/1.1.0/modern-normalize.min.css",
  "https://unpkg.com/@picocss/pico@1.5.5/css/pico.min.css.map",
  "https://unpkg.com/@picocss/pico@1.5.5/css/pico.min.css"
]

remoteJs = [
  "https://www.unpkg.com/howler@2.2.3/dist/howler.core.min.js"
]

css = [
  "css/theme.css",
  "css/fontawesome.css",
  "css/main.css"
]

js = [
  "js/theme.js",
  "js/modal.js",
  "js/gamer.js"
]

lightIcon = "img/fa/moon-stars-duotone.svg"
darkIcon = "img/fa/eclipse-duotone.svg"
