[params]
remoteCss = [
  "https://cdnjs.cloudflare.com/ajax/libs/modern-normalize/1.1.0/modern-normalize.min.css",
  "https://unpkg.com/@picocss/pico@1.5.6/css/pico.min.css.map",
  "https://unpkg.com/@picocss/pico@1.5.6/css/pico.min.css"
]

remoteJs = []

css = [
  "css/theme.css",
  "css/fontawesome.css",
  "css/main.css"
]

js = [
  "js/theme.js",
  "js/modal.js",
  "js/gamer.js"
]

theme.color = "#00a2e8"
theme.lightIcon = "img/fa/sparkles-duotone.svg"
theme.darkIcon = "img/fa/moon-stars-duotone.svg"
theme.notfoundIcon = "galaxy-duotone"
theme.linkIcon = "link-duotone"
theme.extLinkIcon = "arrow-up-right-from-square-duotone"
theme.modalCloseIcon = "circle-xmark-duotone"
