---
name: Check

on:
  - push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: '2.3.12'
      - name: Lint
        run: biome ci
