---
name: Check

on:
  - push

jobs:
  lint:
    name: Lint with ${{ matrix.linter_name }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        linter:
          - eslint
          - stylelint
          - prettier
        include:
          - linter: eslint
            linter_name: ESLint
          - linter: stylelint
            linter_name: Stylelint
          - linter: prettier
            linter_name: Prettier
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Lint
        run: npm run ${{ matrix.linter }}
